CREATE TABLE DBNAME.PRODUCT_STATUS (
    PRODUCT_STATUS_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_STATUS_NAME VARCHAR(30),
    PRODUCT_STATUS_INITIALS VARCHAR(15),
    CONSTRAINT PRODUCT_STATUS_PK PRIMARY KEY (PRODUCT_STATUS_ID)
);

CREATE TABLE DBNAME.PRODUCTS (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCTS_NAME VARCHAR(30),
    MERCHANT_ID INT NOT NULL,
    PRICE INT NOT NULL,
    PRODUCT_STATUS_ID INT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PRODUCTS_PK PRIMARY KEY(PRODUCT_ID),
    CONSTRAINT PRODUCT_PRODUCT_STATUS_FK FOREIGN KEY(PRODUCT_STATUS_ID) REFERENCES PRODUCT_STATUS(PRODUCT_STATUS_ID)
);

CREATE TABLE DBNAME.USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    FULL_NAME VARCHAR(30),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COUNTRY_CODE INT,
    CONSTRAINT USERS_PK PRIMARY KEY(USER_ID)
);

CREATE TABLE DBNAME.ORDERS (
    ORDER_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT,
    ORDER_STATUS VARCHAR(10),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ORDER_PK PRIMARY KEY(ORDER_ID),
    CONSTRAINT ORDER_USER_PK FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE DBNAME.ORDER_ITEMS (
    ORDER_ITEMS_ID INT NOT NULL AUTO_INCREMENT,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT NOT NULL,
    CONSTRAINT ORDER_ITEMS_PK PRIMARY KEY(ORDER_ITEMS_ID),
    CONSTRAINT ORDER_ITEMS_ORDER_FK FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT ORDER_ITEMS_PRODUCTS_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

