INSERT INTO DBNAME.PRODUCT_STATUS (`PRODUCT_STATUS_NAME`,`PRODUCT_STATUS_INITIALS`) VALUES ('ON STOCK', 'ON_STOCK');
INSERT INTO DBNAME.PRODUCT_STATUS (`PRODUCT_STATUS_NAME`, `PRODUCT_STATUS_INITIALS`) VALUES ("OUT OF STOCK", "OUT_OF_STOCK");
INSERT INTO DBNAME.PRODUCTS (`PRODUCTS_NAME`, `MERCHANT_ID`, `PRICE`, `PRODUCT_STATUS_ID`) VALUES ("PRODUCT A", "1", 100, SELECT PRODUCT_STATUS_ID FROM DBNAME.PRODUCT_STATUS WHERE PRODUCT_STATUS_INITIALS = "ON_STOCK");
INSERT INTO DBNAME.PRODUCTS (`PRODUCTS_NAME`, `MERCHANT_ID`, `PRICE`, `PRODUCT_STATUS_ID`) VALUES ("PRODUCT B", "2", 123, SELECT PRODUCT_STATUS_ID FROM DBNAME.PRODUCT_STATUS WHERE PRODUCT_STATUS_INITIALS = "OUT_OF_STOCK");
INSERT INTO DBNAME.USERS (FULL_NAME, COUNTRY_CODE) VALUE ("USER NAME 1", 55);
INSERT INTO DBNAME.PRODUCTS (`PRODUCTS_NAME`, `MERCHANT_ID`, `PRICE`, `PRODUCT_STATUS_ID`) VALUES (SELECT "PRODUCT A", "1", 100, PRODUCT_STATUS_ID FROM DBNAME.PRODUCT_STATUS WHERE PRODUCT_STATUS_INITIALS = "ON_STOCK");
INSERT INTO DBNAME.PRODUCTS (`PRODUCTS_NAME`, `MERCHANT_ID`, `PRICE`, `PRODUCT_STATUS_ID`) VALUES (SELECT "PRODUCT B", "2", 123, PRODUCT_STATUS_ID FROM DBNAME.PRODUCT_STATUS WHERE PRODUCT_STATUS_INITIALS = "OUT_OF_STOCK");
INSERT INTO DBNAME.PRODUCTS (`PRODUCTS_NAME`, `MERCHANT_ID`, `PRICE`, `PRODUCT_STATUS_ID`) VALUES (SELECT 'PRODUCT A', '1', 100, PRODUCT_STATUS_ID FROM DBNAME.PRODUCT_STATUS WHERE PRODUCT_STATUS_INITIALS = 'ON_STOCK');
INSERT INTO DBNAME.PRODUCTS (`PRODUCTS_NAME`, `MERCHANT_ID`, `PRICE`, `PRODUCT_STATUS_ID`) VALUES (SELECT 'PRODUCT A', 1, 100, PRODUCT_STATUS_ID FROM DBNAME.PRODUCT_STATUS WHERE PRODUCT_STATUS_INITIALS = 'ON_STOCK');

INSERT INTO DBNAME.PRODUCTS (`PRODUCTS_NAME`, `MERCHANT_ID`, `PRICE`, `PRODUCT_STATUS_ID`) VALUES ('PRODUCT A', 1, 100, 1);
INSERT INTO DBNAME.PRODUCTS (`PRODUCTS_NAME`, `MERCHANT_ID`, `PRICE`, `PRODUCT_STATUS_ID`) VALUES ('PRODUCT B', 2, 123, 2);
